### ISSUE TITLE
NullPointerException - TrackActivity

### ISSUE THREAD

**Issue by ty221** [fossasia/fossasia-companion-android#52]
From Developer Console:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia/org.fossasia.activities.TrackActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.a.b(java.lang.CharSequence)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.a.b(java.lang.CharSequence)' on a null object reference
at org.fossasia.d.r.a(Unknown Source)
at android.support.v4.app.Fragment.i(Unknown Source)
at android.support.v4.app.w.a(Unknown Source)
at android.support.v4.app.w.a(Unknown Source)
at android.support.v4.app.w.a(Unknown Source)
at android.support.v4.app.w.j(Unknown Source)
at android.support.v4.app.p.onCreate(Unknown Source)
at android.support.v7.app.e.onCreate(Unknown Source)
at org.fossasia.activities.TrackActivity.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5933)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
... 10 more
```

Android: 5.0
Device: Nexus 5 (hammerhead)
Time: 03/10/2015 10:19 UTC

**Comment by batraabhishek** [comment]
Trying to reproduce it... i know it is caused on app resume

*Sent via a really tiny keyboard - please excuse the brevity of the message
