### ISSUE TITLE
NumberFormatException in addToAgenda method in Event Details Fragment

### ISSUE THREAD

**Issue by Vandan-V-Phadke** [fossasia/fossasia-companion-android#61]
java.lang.NumberFormatException: Invalid int: "March1310"
            at java.lang.Integer.invalidInt(Integer.java:138)
            at java.lang.Integer.parse(Integer.java:410)
            at java.lang.Integer.parseInt(Integer.java:367)
            at java.lang.Integer.parseInt(Integer.java:334)
            at org.fossasia.utils.StringUtils.StringToDate(StringUtils.java:143)
            at  org.fossasia.fragments.FossasiaEventDetailsFragment.addToAgenda(FossasiaEventDetailsFragment.java:425)
            at org.fossasia.fragments.FossasiaEventDetailsFragment.onOptionsItemSelected(FossasiaEventDetailsFragment.java:400)
            at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1894)

This happens only when the EventsDetailFragment is launched from the PersonalInfoActivity and not from the TrackActivity

**Comment by ty221** [comment]
Thanks. We will check this issue

**Comment by Vandan-V-Phadke** [comment]
Sir, I am trying to fix this bug. I will issue a PR asap
